In [1]:
import pandas as pd
import numpy as np

In [2]:
data= pd.read_csv('amazon.csv')
Odata = pd.read_csv('retail_demand_dataset.csv')

In [3]:
Odata

,date,store_id,product_id,category,price,discount,units_sold,inventory_level,holiday,promotion,temperature,fuel_price
0,2023-01-01,1,P001,Home,112.0,0,15,157,1,1,19.01,99.28
1,2023-01-02,1,P001,Home,106.4,5,18,139,0,0,22.94,95.47
2,2023-01-03,1,P001,Home,112.0,0,9,130,0,0,12.80,96.21
3,2023-01-04,1,P001,Home,89.6,20,25,105,0,0,32.43,95.83
4,2023-01-05,1,P001,Home,95.2,15,21,84,0,0,24.30,94.93
...,...,...,...,...,...,...,...,...,...,...,...,...
54745,2023-12-27,10,P015,Clothing,442.0,0,17,65,0,0,30.91,94.80
54746,2023-12-28,10,P015,Clothing,442.0,0,14,51,0,1,26.76,99.36
54747,2023-12-29,10,P015,Clothing,419.9,5,15,36,0,0,23.76,96.51
54748,2023-12-30,10,P015,Clothing,442.0,0,21,126,1,0,32.84,99.37
54749,2023-12-31,10,P015,Clothing,442.0,0,15,111,1,0,14.69,96.48

In [4]:
data.info

<bound method DataFrame.info of       product_id                                       product_name  \
0     B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...
1     B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2     B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...
3     B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4     B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...
...          ...                                                ...
1460  B08L7J3T31  Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1461  B01M6453MB  Prestige Delight PRWO Electric Rice Cooker (1 ...
1462  B009P2LIL4  Bajaj Majesty RX10 2000 Watts Heat Convector R...
1463  B00J5DYCCA  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1464  B01486F4G6  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...

                                               category discounted_price  \
0     Computers&Accessories|Accessories&Peripherals|...             ₹399
1     Computers&Accessories|Accessories&Peripherals|...             ₹199
2     Computers&Accessories|Accessories&Peripherals|...             ₹199
3     Computers&Accessories|Accessories&Peripherals|...             ₹329
4     Computers&Accessories|Accessories&Peripherals|...             ₹154
...                                                 ...              ...
1460  Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...             ₹379
1461  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,280
1462  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...           ₹2,219
1463  Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...           ₹1,399
1464  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,863

     actual_price discount_percentage rating rating_count  \
0          ₹1,099                 64%    4.2       24,269
1            ₹349                 43%    4.0       43,994
2          ₹1,899                 90%    3.9        7,928
3            ₹699                 53%    4.2       94,363
4            ₹399                 61%    4.2       16,905
...           ...                 ...    ...          ...
1460         ₹919                 59%      4        1,090
1461       ₹3,045                 25%    4.1        4,118
1462       ₹3,080                 28%    3.6          468
1463       ₹1,890                 26%      4        8,031
1464       ₹3,690                 22%    4.3        6,987

                                          about_product  \
0     High Compatibility : Compatible With iPhone 12...
1     Compatible with all Type C enabled devices, be...
2     【 Fast Charger& Data Sync】-With built-in safet...
3     The boAt Deuce USB 300 2 in 1 cable is compati...
4     [CHARGE & SYNC FUNCTION]- This cable comes wit...
...                                                 ...
1460  SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...
1461                       230 Volts, 400 watts, 1 Year
1462  International design and styling|Two heat sett...
1463  Fan sweep area: 230 MM ; Noise level: (40 - 45...
1464  Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...

                                                user_id  \
0     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
1     AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
2     AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...
3     AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...
4     AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...
...                                                 ...
1460  AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...
1461  AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...
1462  AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...
1463  AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...
1464  AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...

                                              user_name  \
0     Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
1     ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
2     Kunal,Himanshu,viswanath,sai niharka,saqib mal...
3     Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...
4     rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...
...                                                 ...
1460  Prabha ds,Raghuram bk,Real Deal,Amazon Custome...
1461  Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...
1462  Nehal Desai,Danish Parwez,Amazon Customer,Amaz...
1463  Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...
1464  Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...

                                              review_id  \
0     R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
1     RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
2     R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...
3     R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...
4     R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...
...                                                 ...
1460  R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...
1461  R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...
1462  R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...
1463  R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...
1464  R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...

                                           review_title  \
0     Satisfied,Charging is really fast,Value for mo...
1     A Good Braided Cable for Your Type C Device,Go...
2     Good speed for earlier versions,Good Product,W...
3     Good product,Good one,Nice,Really nice product...
4     As good as original,Decent,Good one for second...
...                                                 ...
1460  Received the product without spanner,Excellent...
1461  ok,everything was good couldn't return bcoz I ...
1462  very good,Work but front melt after 2 month,Go...
1463  Fan Speed is slow,Good quality,Good product,go...
1464  Works perfect,Ok good product,Nice Product. Re...

                                         review_content  \
0     Looks durable Charging is fine tooNo complains...
1     I ordered this cable to connect my phone to An...
2     Not quite durable and sturdy,https://m.media-a...
3     Good product,long wire,Charges good,Nice,I bou...
4     Bought this instead of original apple, does th...
...                                                 ...
1460  I received product without spanner,Excellent p...
1461  ok,got everything as mentioned but the measuri...
1462  plastic but cool body ,u have to find sturdy s...
1463  I have installed this in my kitchen working fi...
1464  It does it job perfectly..only issue is temp c...

                                               img_link  \
0     https://m.media-amazon.com/images/W/WEBP_40237...
1     https://m.media-amazon.com/images/W/WEBP_40237...
2     https://m.media-amazon.com/images/W/WEBP_40237...
3     https://m.media-amazon.com/images/I/41V5FtEWPk...
4     https://m.media-amazon.com/images/W/WEBP_40237...
...                                                 ...
1460  https://m.media-amazon.com/images/I/41fDdRtjfx...
1461  https://m.media-amazon.com/images/I/41gzDxk4+k...
1462  https://m.media-amazon.com/images/W/WEBP_40237...
1463  https://m.media-amazon.com/images/W/WEBP_40237...
1464  https://m.media-amazon.com/images/W/WEBP_40237...

                                           product_link
0     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1     https://www.amazon.in/Ambrane-Unbreakable-Char...
2     https://www.amazon.in/Sounce-iPhone-Charging-C...
3     https://www.amazon.in/Deuce-300-Resistant-Tang...
4     https://www.amazon.in/Portronics-Konnect-POR-1...
...                                                 ...
1460  https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461  https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462  https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463  https://www.amazon.in/Havells-Ventilair-230mm-...
1464  https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

[1465 rows x 16 columns]>

In [5]:
Odata.info

<bound method DataFrame.info of              date  store_id product_id  category  price  discount  units_sold  \
0      2023-01-01         1       P001      Home  112.0         0          15
1      2023-01-02         1       P001      Home  106.4         5          18
2      2023-01-03         1       P001      Home  112.0         0           9
3      2023-01-04         1       P001      Home   89.6        20          25
4      2023-01-05         1       P001      Home   95.2        15          21
...           ...       ...        ...       ...    ...       ...         ...
54745  2023-12-27        10       P015  Clothing  442.0         0          17
54746  2023-12-28        10       P015  Clothing  442.0         0          14
54747  2023-12-29        10       P015  Clothing  419.9         5          15
54748  2023-12-30        10       P015  Clothing  442.0         0          21
54749  2023-12-31        10       P015  Clothing  442.0         0          15

       inventory_level  holiday  promotion  temperature  fuel_price
0                  157        1          1        19.01       99.28
1                  139        0          0        22.94       95.47
2                  130        0          0        12.80       96.21
3                  105        0          0        32.43       95.83
4                   84        0          0        24.30       94.93
...                ...      ...        ...          ...         ...
54745               65        0          0        30.91       94.80
54746               51        0          1        26.76       99.36
54747               36        0          0        23.76       96.51
54748              126        1          0        32.84       99.37
54749              111        1          0        14.69       96.48

[54750 rows x 12 columns]>

In [6]:
Odata.shape

(54750, 12)

In [7]:
Odata.describe()

,store_id,price,discount,units_sold,inventory_level,holiday,promotion,temperature,fuel_price
count,54750.000000,54750.00000,54750.000000,54750.000000,54750.000000,54750.000000,54750.000000,54750.000000,54750.000000
mean,5.500000,255.97775,5.024475,19.365553,78.736511,0.287671,0.297790,25.011704,94.999164
std,2.872308,135.82799,6.125334,5.954674,35.996147,0.452681,0.457291,5.024495,2.001758
min,1.000000,10.40000,0.000000,0.000000,20.000000,0.000000,0.000000,3.960000,86.070000
25%,3.000000,140.60000,0.000000,15.000000,48.000000,0.000000,0.000000,21.620000,93.650000
50%,5.500000,263.15000,5.000000,19.000000,77.000000,0.000000,0.000000,25.020000,95.000000
75%,8.000000,370.50000,10.000000,23.000000,106.000000,1.000000,1.000000,28.407500,96.360000
max,10.000000,499.00000,20.000000,46.000000,186.000000,1.000000,1.000000,46.470000,103.300000

In [8]:
Odata.isnull().sum()

date               0
store_id           0
product_id         0
category           0
price              0
discount           0
units_sold         0
inventory_level    0
holiday            0
promotion          0
temperature        0
fuel_price         0
dtype: int64

In [9]:
Odata['date']= pd.to_datetime(Odata['date'])

In [10]:
Odata['Year']= Odata['date'].dt.year
Odata['Month']= Odata['date'].dt.month
Odata['Day']= Odata['date'].dt.day
Odata['Weekday']= Odata['date'].dt.weekday

In [11]:
Odata["lag_1"] = Odata["units_sold"].shift(1)
Odata["lag_7"] = Odata["units_sold"].shift(7)
Odata["lag_14"] = Odata["units_sold"].shift(14)

In [12]:
Odata2= Odata.copy()

In [13]:
Odata2.head()

,date,store_id,product_id,category,price,discount,units_sold,inventory_level,holiday,promotion,temperature,fuel_price,Year,Month,Day,Weekday,lag_1,lag_7,lag_14
0,2023-01-01,1,P001,Home,112.0,0,15,157,1,1,19.01,99.28,2023,1,1,6,NaN,NaN,NaN
1,2023-01-02,1,P001,Home,106.4,5,18,139,0,0,22.94,95.47,2023,1,2,0,15.0,NaN,NaN
2,2023-01-03,1,P001,Home,112.0,0,9,130,0,0,12.80,96.21,2023,1,3,1,18.0,NaN,NaN
3,2023-01-04,1,P001,Home,89.6,20,25,105,0,0,32.43,95.83,2023,1,4,2,9.0,NaN,NaN
4,2023-01-05,1,P001,Home,95.2,15,21,84,0,0,24.30,94.93,2023,1,5,3,25.0,NaN,NaN

In [14]:
Odata2.dropna()

,date,store_id,product_id,category,price,discount,units_sold,inventory_level,holiday,promotion,temperature,fuel_price,Year,Month,Day,Weekday,lag_1,lag_7,lag_14
14,2023-01-15,1,P001,Home,112.0,0,17,26,1,0,31.37,94.42,2023,1,15,6,36.0,26.0,15.0
15,2023-01-16,1,P001,Home,112.0,0,12,145,0,0,26.73,95.91,2023,1,16,0,17.0,7.0,18.0
16,2023-01-17,1,P001,Home,112.0,0,17,128,0,1,15.41,94.95,2023,1,17,1,12.0,13.0,9.0
17,2023-01-18,1,P001,Home,112.0,0,10,118,0,0,37.32,94.62,2023,1,18,2,17.0,24.0,25.0
18,2023-01-19,1,P001,Home,89.6,20,24,94,0,0,30.71,96.50,2023,1,19,3,10.0,17.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54745,2023-12-27,10,P015,Clothing,442.0,0,17,65,0,0,30.91,94.80,2023,12,27,2,19.0,14.0,12.0
54746,2023-12-28,10,P015,Clothing,442.0,0,14,51,0,1,26.76,99.36,2023,12,28,3,17.0,19.0,23.0
54747,2023-12-29,10,P015,Clothing,419.9,5,15,36,0,0,23.76,96.51,2023,12,29,4,14.0,27.0,26.0
54748,2023-12-30,10,P015,Clothing,442.0,0,21,126,1,0,32.84,99.37,2023,12,30,5,15.0,28.0,17.0
54749,2023-12-31,10,P015,Clothing,442.0,0,15,111,1,0,14.69,96.48,2023,12,31,6,21.0,22.0,25.0

In [20]:
features = [
    "price",
    "discount",
    "inventory_level",
    "promotion",
    "holiday",
    "Month",
    "Weekday",
    "lag_1",
    "lag_7",
    "lag_14"
]

In [21]:
target = "units_sold"

In [22]:
from sklearn.model_selection import train_test_split

In [25]:
x= Odata[features]
y= Odata[target]

x_train,x_test, y_train, y_test = train_test_split(
    x,y,test_size = 0.2, random_state= 42
)

In [26]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(x_train, y_train)

RandomForestRegressor()